//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazyn2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int id_warehouse { get; set; }
        public int code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime created { get; set; }
        public int id_user { get; set; }
    
        public virtual User User { get; set; }
    }
}
